import { QuizType } from "@/types";
import { cookies } from "next/headers";

export async function sendAutoNotification(
  yearId: number,
  type: "link" | QuizType,
  id: number
) {
  const res = await fetch(
    `${process.env.NEXT_PUBLIC_API_URL}/notifications/topics/${yearId}`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${cookies().get("jwt")!.value}`,
      },
      body: JSON.stringify({
        type: "autogenerated",
        yearId,
        notify: {
          links: type === "link" ? [id] : [],
          mcqQuizzes: type === "mcq" ? [id] : [],
          writtenQuizzes: type === "written" ? [id] : [],
        },
      }),
    }
  );
  await res.json();
}
